using System;
using NUnit.Framework;
using SharpBucket.V2;
using SharpBucket.V2.EndPoints;
using SharpBucket.V2.Pocos;
using SharpBucketTests.V2.Pocos;
using Shouldly;

namespace SharpBucketTests.V2.EndPoints
{
    [TestFixture]
    public class ProjectResourceTests
    {
        private SharpBucketV2 sharpBucket;
        private TeamsEndPoint teamsEndPoint;
        private string teamName;
        private TeamResource teamResource;

        [OneTimeSetUp]
        public void Init()
        {
            sharpBucket = TestHelpers.SharpBucketV2;
            teamsEndPoint = sharpBucket.TeamsEndPoint();

            teamName = teamsEndPoint.GetUserTeamsWithAdminRole()[0].username;
            teamResource = teamsEndPoint.TeamResource(teamName);
        }

        [Test]
        public void PutGetDeleteProject_InTeam_AllOperationsWorks()
        {
            var projectKey = "Test_" + Guid.NewGuid().ToString("N"); // must start by a letter
            var projectResource = teamResource.ProjectResource(projectKey);
            var newProject = new Project
            {
                name = "Name of " + projectKey,
                description = "project generated by test " + nameof(PutGetDeleteProject_InTeam_AllOperationsWorks),
                is_private = true
            };

            try
            {
                // create with PUT
                var createdProject = projectResource.PutProject(newProject);
                createdProject.ShouldBeFilled();
                createdProject.key.ShouldBe(projectKey);
                createdProject.name.ShouldBe(newProject.name);
                createdProject.description.ShouldBe(newProject.description);
                createdProject.is_private.ShouldBe(newProject.is_private);
                createdProject.owner.username.ShouldBe(teamName);

                // get
                var getProject = projectResource.GetProject();
                getProject.ShouldBeEquivalentTo(createdProject);

                // update
                getProject.description += " -- altered description";
                var updatedProject = projectResource.PutProject(getProject);
                updatedProject.ShouldBeEquivalentExceptUpdateDateTo(getProject);
            }
            finally
            {
                // delete
                projectResource.DeleteProject();
            }
        }
    }
}
