using System;
using System.Threading.Tasks;
using NUnit.Framework;
using SharpBucket.V2.EndPoints;
using SharpBucket.V2.Pocos;
using SharpBucketTests.V2.Pocos;
using Shouldly;

namespace SharpBucketTests.V2.EndPoints
{
    [TestFixture]
    public class ProjectResourceTests
    {
        private ProjectsResource UserWorkspaceProjectsResource { get; set; }

        [OneTimeSetUp]
        public void Init()
        {
            var sharpBucket = TestHelpers.SharpBucketV2;
            var workspacesEndPoint = sharpBucket.WorkspacesEndPoint();

            this.UserWorkspaceProjectsResource = workspacesEndPoint
                                                .WorkspaceResource(TestHelpers.AccountName)
                                                .ProjectsResource;
        }

        [Test]
        public void PutGetDeleteProject_InUserWorkspace_AllOperationsWorks()
        {
            var projectKey = "Test_" + Guid.NewGuid().ToString("N"); // must start by a letter
            var projectResource = UserWorkspaceProjectsResource.ProjectResource(projectKey);
            var newProject = new Project
            {
                name = "Name of " + projectKey,
                description = "project generated by test " + nameof(PutGetDeleteProject_InUserWorkspace_AllOperationsWorks),
                is_private = true
            };

            try
            {
                // create with PUT
                var createdProject = projectResource.PutProject(newProject);
                createdProject.ShouldBeFilled();
                createdProject.key.ShouldBe(projectKey);
                createdProject.name.ShouldBe(newProject.name);
                createdProject.description.ShouldBe(newProject.description);
                createdProject.is_private.ShouldBe(newProject.is_private);
                createdProject.workspace.slug.ShouldBe(TestHelpers.AccountName);

                // get
                var getProject = projectResource.GetProject();
                getProject.ShouldBeEquivalentTo(createdProject);

                // update
                getProject.description += " -- altered description";
                var updatedProject = projectResource.PutProject(getProject);
                updatedProject.ShouldBeEquivalentExceptUpdateDateTo(getProject);
            }
            finally
            {
                // delete
                projectResource.DeleteProject();
            }
        }

        [Test]
        public async Task PutAsyncGetAsyncDeleteAsyncProject_InUserWorkspace_AllOperationsWorks()
        {
            var projectKey = "Test_" + Guid.NewGuid().ToString("N"); // must start by a letter
            var projectResource = UserWorkspaceProjectsResource.ProjectResource(projectKey);
            var newProject = new Project
            {
                name = "Name of " + projectKey,
                description = "project generated by test " + nameof(PutAsyncGetAsyncDeleteAsyncProject_InUserWorkspace_AllOperationsWorks),
                is_private = true
            };

            try
            {
                // create with PUT
                var createdProject = await projectResource.PutProjectAsync(newProject);
                createdProject.ShouldBeFilled();
                createdProject.key.ShouldBe(projectKey);
                createdProject.name.ShouldBe(newProject.name);
                createdProject.description.ShouldBe(newProject.description);
                createdProject.is_private.ShouldBe(newProject.is_private);
                createdProject.workspace.slug.ShouldBe(TestHelpers.AccountName);

                // get
                var getProject = await projectResource.GetProjectAsync();
                getProject.ShouldBeEquivalentTo(createdProject);

                // update
                getProject.description += " -- altered description";
                var updatedProject = await projectResource.PutProjectAsync(getProject);
                updatedProject.ShouldBeEquivalentExceptUpdateDateTo(getProject);
            }
            finally
            {
                // delete
                await projectResource.DeleteProjectAsync();
            }
        }
    }
}
